embed_html:
    path: "../images/storage/full/"
    model_name: "sv_corona_full_embed_model.html"
    save_name : "sv_corona_full_embed_final.html"
    css_name: "plusultra.css"
    bucket: 'sv-covid19'
    bucket_folder: "site/full"

br_cumulative:
    bucket: 'sv-covid19'
    bucket_folder: "site/graphs/cumulative"
    path_save: '../images/storage/cumulativo/'
    save_name: 'brasil_por_estado_{}.html' ##get a format by var_options
    var_options: [confirmed, deaths]
    in_cities: ['BRASIL','BRASIL SEM SP','SP', 'RJ']
    color_options: ['novo', 'novo_storage']

br_daily:
    bucket: 'sv-covid19'
    bucket_folder: "site/graphs/daily"
    path_save: '../images/storage/diario/'
    ### var and save_name
    var_options: {'cases':'brasil_lin_total.html','deaths':'brasil_lin_mortes.html'}
    color_options: 'novo_storage'
    selection: 'BRASIL'


br_map:
    path_save: '../maps/'
    save_name: 'cidades_estados.html'
    bucket: 'sv-covid19'
    bucket_folder: "site/maps"

vale_map:
    path_save: '../maps/'
    save_name: 'mapa_vale.html'
    bucket: 'sv-covid19'
    bucket_folder: "site/maps"


ms_table:
    rename_cols: {
        'região':"regiao", 
        'estado':'state',
        "data":'date',
        'casosNovos':'new_cases',
        'casosAcumulados':'confirmed',
        'obitosNovos':'new_deaths',
        'obitosAcumulados':'deaths'
        }
    date_format: "%Y-%m-%d"